language: python
sudo: required
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
  ./.travis/install.sh
script:
  - pytest --workers auto
  - find src -iname "*.py" | xargs pylint
  - find scripts -iname "*.py" | xargs pylint
